---

#see ../vars/main.yml for list of packages
- name: install required packages
  apt:
    force_apt_get: yes
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ apt_package_list }}"
