#CS requires a different way of requesting RAM
#and also needs to vary this by dropping the h_vmem part for some jobs
# see https://hpc.cs.ucl.ac.uk/wp-content/uploads/sites/21/2022/01/SGE-Guide_12_2021.pdf p19
# which notes that sometimes h_vmem should be omitted as it causes memory errors

#we also run jobs locally in parallel on the skinner node not via qsub
- config:
    qsub:
        memfmt: "#$ -l tmem={mem},h_vmem={mem}"
    exec_mode:      "parallel"
