#
# config related to the human genome reference sequence reads will be mapped against (GRCh38)
# also:
#  ensembl annotation (GRCh38.107)
#  dbsnp
#  GATK resource bundle
#

- config:
    ref:
      #temporary download location of initial FASTA
      tmp_dir:  "references/GRCh38_noalt_withdecoys/tmp"

      #download URL and file list
      base_url:  "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids"
      base_name: "GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set" 
      fasta:     "{%ref/base_name}.fna.gz"
      md5:       "md5checksums.txt"
      readme:    "README_analysis_sets.txt"

      #location of the final checked, recompressed FASTA
      base_dir: "references/GRCh38_noalt_withdecoys"

      #reference genome sequence FASTA recompressed with bgzip
      fasta_bgz:   "{%ref/base_dir}/{%ref/fasta}"

      #associated index files
      fasta_gzi:  "{%ref/fasta_bgz}.gzi"
      fasta_fai:  "{%ref/fasta_bgz}.fai"
      fasta_dict: "{%ref/base_dir}/{%ref/base_name}.dict"

      #GATK3 cannot use compressed reference
      uncompressed:     "{%ref/base_dir}/{%ref/base_name}.fna"
      uncompressed_fai: "{%ref/uncompressed}.fai"

      #ensembl annotation
      annot_url:  "http://ftp.ensembl.org/pub/release-107/gff3/homo_sapiens"
      annot_gff3: "Homo_sapiens.GRCh38.107.gff3.gz"
      annot_chk:  "CHECKSUMS"
      annot_dir:  "annotation/ensembl_107"

      #dbSNP
      #dbsnp_url: "https://ftp.ncbi.nih.gov/snp/latest_release/VCF"
      #dbsnp_vcf: "GCF_000001405.39.gz"
      #dbsnp_idx: "GCF_000001405.39.gz.tbi"
      #final_vcf: "GCF_000001405.39.renamed.vcf.gz"
      #dbsnp_dir: "dbsnp/build_155"
      dbsnp_url: "https://ftp.ncbi.nih.gov/snp/latest_release/VCF"
      dbsnp_vcf: "GCF_000001405.40.gz"
      dbsnp_idx: "GCF_000001405.40.gz.tbi"
      final_vcf: "GCF_000001405.40.renamed.vcf.gz"
      dbsnp_dir: "dbsnp/build_156"

      #assembly report to map chromosome names from dbSNP to assembly
      assembly_report_url:   "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14"
      assembly_report_file:  "GCF_000001405.40_GRCh38.p14_assembly_report.txt"
      assembly_name_mapping: "NCBI2UCSC_mapping"

      #gatk resource bundle
      bundle_dir: "resources/gatk_bundle"
      bundle_dir_version: "v0"
      indels1: "{%ref/bundle_dir}/{%ref/bundle_dir_version}/Homo_sapiens_assembly38.known_indels.vcf.gz"
      indels2: "{%ref/bundle_dir}/{%ref/bundle_dir_version}/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"

      #cram md5 based reference sequences
      cram_ref_dir: "references/cram_ref_by_md5"