### SCRIPT AUTOMATICALLY GENERATED BY MUTEIN PIPELINE (UCL-ARC 2022) ###
run=qsub
install_dir=$1
script=${install_dir}Pipelines/libs/pipeline_qsubber.py

#config=${install_dir}Pipelines/geneanalysis/config/batch_dataset_prep.yml

#config=${install_dir}Pipelines/geneanalysis/config/batch_gene_1_pdbs.yml
#config=${install_dir}Pipelines/geneanalysis/config/batch_gene_2_rep.yml
#config=${install_dir}Pipelines/geneanalysis/config/batch_gene_3_prep.yml
#config=${install_dir}Pipelines/geneanalysis/config/batch_gene_4_tasks.yml
#config=${install_dir}Pipelines/geneanalysis/config/batch_gene_5_agg.yml

config=${install_dir}Pipelines/geneanalysis/config/batch_pdb_1_rep.yml
#config=${install_dir}Pipelines/geneanalysis/config/batch_pdb_2_prep.yml
#config=${install_dir}Pipelines/geneanalysis/config/batch_pdb_3_tasks.yml
#config=${install_dir}Pipelines/geneanalysis/config/batch_pdb_4_agg.yml

echo "EXE PATH=$install_dir"
echo "CURRENT=$PWD"
echo "~~~~~~~~~~~~~~~~~~ Call python script ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
python ${script} $install_dir $PWD ${config} $run notch NOTCH1 1pb5
