### SCRIPT AUTOMATICALLY GENERATED BY MUTEIN PIPELINE (UCL-ARC 2022) ###

#Open file in the data directory and then...
#../Mutein/Pipelines/geneanalysis/ppl_notch_NOTCH1.sh /home/rachel/UCL/github/Mutein/
run=qsub
install_dir=$1
script=${install_dir}Pipelines/libs/pipeline_qsubber.py
config=${install_dir}Pipelines/geneanalysis/config/batch_pdb.yml
echo "EXE PATH=$install_dir"
echo "CURRENT=$PWD"

module load python3/recommended
python ${script} $install_dir $PWD ${config} $run notch NOTCH1 AF-P46531-F1-model_v2