### SCRIPT AUTOMATICALLY GENERATED BY MUTEIN PIPELINE (UCL-ARC 2022) ###
run=qsub
install_dir=$1
script=${install_dir}Pipelines/lib/pipeline_qsubber.py
config=${install_dir}Pipelines/geneanalysis/config/batch_genestitch.yml
echo "EXE PATH=$install_dir"
echo "CURRENT=$PWD"
module load python3/recommended
python ${script} $install_dir $PWD ${config} $run notch NOTCH1 x
