### SCRIPT AUTOMATICALLY GENERATED BY MUTEIN PIPELINE (UCL-ARC 2022) ###
run=qsub
install_dir=$1
script=${install_dir}Pipelines/libs/pipeline_qsubber.py
config=${install_dir}Pipelines/geneanalysis/config/batch_pdb.yml
echo "EXE PATH=$install_dir"
echo "CURRENT=$PWD"
module load python3/recommended
echo "~~~~~~~~~~~~~~~~~~ Call python script ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
python ${script} $install_dir $PWD ${config} $run notch NOTCH1 AF-P46531-F1-model_v2
python ${script} $install_dir $PWD ${config} $run notch NOTCH1 1yyh
python ${script} $install_dir $PWD ${config} $run notch NOTCH1 2f8x
python ${script} $install_dir $PWD ${config} $run notch NOTCH1 2f8y
python ${script} $install_dir $PWD ${config} $run notch NOTCH1 3i08
python ${script} $install_dir $PWD ${config} $run notch NOTCH1 3l95
python ${script} $install_dir $PWD ${config} $run notch NOTCH1 3nbn
python ${script} $install_dir $PWD ${config} $run notch NOTCH1 3v79
python ${script} $install_dir $PWD ${config} $run notch NOTCH1 5fm9
python ${script} $install_dir $PWD ${config} $run notch NOTCH1 5fma
python ${script} $install_dir $PWD ${config} $run notch NOTCH1 5l0r
python ${script} $install_dir $PWD ${config} $run notch NOTCH1 6py8
