---

# create mdadm /dev/md0 raid0 device
- name: create raid0
  shell: |
    mdadm --create --verbose /dev/md0 --level=0 --raid-devices=4 {{ raid0_devs }} && \
    mdadm --detail --scan >> /etc/mdadm/mdadm.conf && \
    update-initramfs -u
    
#UUID=530b5d84-35d1-487f-8b6f-03aaf86e4239 /mnt/raid0 xfs rw,relatime,attr2,inode64,noquota 0 1