# Snakemake profile

cores: 999
local-cores: 2
jobs: 99
cluster: "qsub -cwd -V -N {rule}_{wildcards}_$(date +%Y%m%d%H%M%S).${{RANDOM}}
  -l h_rt={params.time},mem={params.mem},tmpfs={params.tmpfs} -pe smp {threads} 
  -e logs/\\$JOB_NAME.err -o logs/\\$JOB_NAME.out"
#cluster-cancel: "qdel {jobname}" #not working!
use-conda: True
latency-wait: 30
#jobscript: /home/ccaervi/snakemake-drmaa/jobscript.sh ##does it need #!/bin/bash -l
#default-resources: "mem_mb=10" #,disk_mb=10" # tmpdir=/tmp"

#force only one conda create to run at a time
resources: conda_lock=1

# #auxillary config file - now added from commandline using alias to provide full path easily
# configfile: "mutein.yaml"