---
id: 'TASKS'
qsub_id: 'tasks'
pipe_dir: 'Pipelines/foldx/python/'
script: 'ga__runner'
time: '10:00:0'
cores: "4"
dependency: '-1'
array: -1
arrayfile: "params"
inputs: "runs=f@repairs=x"
active: 'Y'
---
id: 'VTASKS'
qsub_id: 'vtasks'
pipe_dir: 'Pipelines/foldx/python/'
script: 'ga__runner'
time: '10:00:0'
cores: "4"
dependency: 'TASKS'
array: -1
arrayfile: "vparams"
inputs: "runs=g@repairs=x@variant=*"
active: 'Y'
---
id: 'AGG'
qsub_id: 'agg'
pipe_dir: 'Pipelines/foldx/python/'
script: 'ga__runner'
time: '1:00:0'
cores: "1"
dependency: 'VTASKS'
array: 0
inputs: "runs=hij@repairs=x@variant=*"
active: 'Y'
---
id: 'CLEAN'
qsub_id: 'clean'
pipe_dir: 'Pipelines/foldx/python/'
script: 'ga__runner'
time: '1:00:0'
cores: "1"
dependency: 'AGG'
array: 0
inputs: "runs=x"
active: 'Y'
---