---
id: 'REP'
qsub_id: 'repair'
pipe_dir: 'Pipelines/foldx/python/'
script: 'ga__runner'
time: '20:00:0'
cores: "4"
dependency: '-1'
array: 0
inputs: "runs=cde@repairs=10@chunk=200@vchunk=200@variant=*"
active: 'Y'
--- 