---
id: 'PRAM'
qsub_id: 'pram'
pipe_dir: 'Pipelines/foldx/python/'
script: 'ga__runner'
time: '1:00:0'
cores: "1"
dependency: '-1'
array: 0
inputs: "runs=d@repairs=x@chunk=200@vchunk=200@variant=*"
active: 'Y'
---
id: 'VPRAM'
qsub_id: 'vpram'
pipe_dir: 'Pipelines/foldx/python/'
script: 'ga__runner'
time: '1:00:0'
cores: "1"
dependency: '-1'
array: 0
inputs: "runs=e@repairs=x@chunk=500@vchunk=500@variant=*"
active: 'Y'
--- 