---
id: 'REP'
qsub_id: 'repair'
pipe_dir: 'Pipelines/foldx/python/'
script: 'ga__runner'
time: '20:00:0'
cores: "4"
dependency: '-1'
array: -1
arrayfile: "unpdbs"
inputs: "runs=c@repairs=10@missing=Y@chunk=500@vchunk=500@variant=*"
active: 'Y'
---