---
id: 'PRAM'
qsub_id: 'pram'
pipe_dir: 'Pipelines/foldx/python/'
script: 'ga__runner'
time: '5:00:0'
cores: "1"
dependency: '-1'
array: 0
inputs: "runs=de@repairs=x@chunk=500@vchunk=500@variant=*"
active: 'Y'
---