#core YAMLmake config
- config:
    ym:
        prefix:             "mut."
        remote_delay_secs:  "10"
        stale_output_file:  "ignore"
        stale_output_dir:   "ignore"
        failed_output_file: "stale"
        failed_output_dir:  "stale"
        missing_parent_dir: "create"
        recycle_bin:        "recycle_bin"
        job_count:          "YM_NJOBS"
        job_number:         "YM_JOB_NUMBER"
        bash_setup:         "source ~/.bashrc\nset -euo pipefail\nset +o history"
        #conda_setup:        "source ~/mambaforge/etc/profile.d/conda.sh"
        conda_prefix:       "{$MUT_PREFIX}"

    qsub:
        template: "default"
        time:     "02:00:00"
        mem:      "4G"
        tmpfs:    "10G"
        pe:       "smp"
        cores:    "1"

    env:
        #provide dummy values to prevent bash strict mode causing unbound variable errors in
        #~/mambaforge/envs/mutein_gatk4/etc/conda/activate.d/openjdk_activate.sh
        JAVA_HOME: "-"
        JAVA_LD_LIBRARY_PATH: "-"

    working_dir:    "{$MUT_DATA}"
    conf_dir:       "{$MUT_DIR}/Pipelines/yamlmake"
    conda_channels: "--override-channels -c conda-forge -c defaults -c bioconda"
