#this file is listed as an input to the reference download action
#therefore any changes can trigger a rerun of that action
- config:
    ref:
      base_url: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids"
      fasta:    "GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna.gz"
      md5:      "md5checksums.txt"
      readme:   "README_analysis_sets.txt"
      base_dir: "references/GRCh38_noalt_withdecoys"
      tmp_dir:  "references/GRCh38_noalt_withdecoys/tmp"
