---

- name: create mutein user
  ansible.builtin.user:
    name: mutein
    state: present

- name: authorise a key for mutein user
  authorized_key:
    user: mutein
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJmnPfZdRnsntaxuXMHTWH3BczHgjTYyR1fEYP4lOjjR ccaervi@ubuntu-vm1"

- name: create mutein scratch folder
  ansible.builtin.file:
    path: /mnt/raid0/mutein
    state: directory
    owner: mutein
    group: mutein

- name: generate mutein github keypair
  community.crypto.openssh_keypair:
    path: /home/mutein/.ssh/id_ed25519
    type: ed25519

- name: add user to slurm
  shell: |
    sacctmgr --immediate add user mutein account=compute-acc
