#!/bin/bash

set -eu
source ~/.mutein_settings
conda activate ${MUT_PREFIX}bwa
export SGE_TASK_ID
JOBLIST=$1

$(vc_extract_params --params "cores accession" --tasklist ${TASKLIST})

SAMTOOLS_TMP=${USER}-${SGE_JOB_ID}-${SGE_TASK_ID}-${RANDOM}
mkdir -p /tmp/${SAMTOOLS_TMP}

#array job commands for step1:
#map with bwa mem, add readgroup tag to say "these are all from the same sample"
#sort mapped read by mapping position, output to bam file
bwa mem -t 4 ${REF} ${READS1} ${READS2} \
| samtools addreplacerg \
    -r \"ID:${DATASET}_${SUBSET}_${ACCESSION}\" \
    -r \"SM:${DATASET}_${SUBSET}_${ACCESSION}\" - \
| samtools sort -T /tmp/${SAMTOOLS_TMP} -O bam -m 2G - \
> ${BAMOUT}

rm -rf /tmp/${SAMTOOLS_TMP}
