---
- name: restart slurmdbd
  systemd:
    name: slurmdbd
    state: restarted

- name: restart slurmctld
  systemd:
    name: slurmctld
    state: restarted

- name: restart slurmd
  systemd:
    name: slurmd
    state: restarted

- name: update grub
  shell: update-grub
