#!/usr/bin/env python

import sys
MIN_PYTHON = (3, 7)
if sys.version_info < MIN_PYTHON:
    sys.exit("Python %s.%s or later is required.\n" % MIN_PYTHON)

import argparse
import yamlmake as ym

def run_main():
    args,parser = parse_args()

    if args.yaml and args.qsub:
        print("Cannot use --yaml and --qsub at the same time. --qsub is only used internally by yamlmake and should not normally be used the user directly.")
        exit(1)

    if args.yaml != None:
        #process a yamlmake file
        pipeline = ym.parse_yaml(args.yaml)
        exit(ym.process(pipeline,args.yaml,args=args))

    elif args.qsub != None:
        #carry out a job on a compute node spawned from qsub (gridengine)
        ym.qsub_execute_job(args.qsub)

    else:
        parser.print_help()

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--yaml',help="YAML pipeline definition file to execute")
    parser.add_argument('--log-dir',help="provide custom path for the logging folder")
    parser.add_argument('--no-logs',action='store_true',help="do not save any status or error messages to the main log files")
    parser.add_argument('--prefix',default='ym-',help="provide prefix for job names and log files")
    parser.add_argument('--run-only',action='extend',nargs="+",type=str,help="run only the named action(s)")
    parser.add_argument('--run-from',help="only start running at the named action")
    parser.add_argument('--run-until',help="do not run beyond the named action")
    parser.add_argument('--module',action='extend',nargs="+",type=str,help="only run the named module(s)")
    parser.add_argument('--dry-run','--dryrun',action='store_true',help="do not run anything, just report what would have been run")
    parser.add_argument('--quiet',action='store_true',help="do not print any status messages to screen")
    parser.add_argument('--conf',help="YAML string containing configuration overrides, eg 'exec: \"local\"' or 'ym: { aggregate: \"10\" }'")

    parser.add_argument('--qsub',help="used internally to execute a job using qsub")
    args = parser.parse_args()
    return args,parser

if __name__ == "__main__":
    run_main()
