fm:
  prefix:               "mut."
  stale_output_file:    "recycle"
  stale_output_dir:     "ignore"
  missing_parent_dir:   "create"

working_dir:          "/lustre/scratch/scratch/{$USER}/549_mutein"
