- config:
    dataset_id: "yokoyama2019"

    subset_id:
      - "EGAD00001004464"
      - "EGAD00001004462"
      - "EGAD00010001631"

    credentials: "/SAN/medic/MuteinScratch/549_mutein/config/private_config1.json"
