#!/usr/bin/env python

import argparse
import fakemake as fm

def run_main():
    args,parser = parse_args()

    if args.yaml != None:
        #process a fakemake file
        pipeline = fm.parse_yaml(args.yaml)
        config = fm.setup_config(pipeline)
        fm.process(config,pipeline)

    elif args.qsub != None:
        #carry out a job on a compute node spawned from qsub (gridengine)
        fm.qsub_execute_job(args.qsub)

    else:
        parser.print_help()

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--yaml',default=None,help="YAML pipeline definition file to execute")
    parser.add_argument('--qsub',default=None,help="used internally to execute a job using qsub")
    args = parser.parse_args()
    return args,parser

if __name__ == "__main__":
    run_main()
