#!/usr/bin/env python

import argparse
import fakemake as fm

def run_main():
    args = parse_args()
    pipeline = fm.parse_yaml(args.file)
    config = fm.setup_config(pipeline)
    fm.process(config,pipeline)

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('file')
    args = parser.parse_args()
    return args

if __name__ == "__main__":
    run_main()
