---
# this playbook assumes the remote linux compute node uses a debian based linux
# as it uses apt to install packages
# cd into this folder then:
# launch VM from AWS console and get it's public IP (also from AWS console)
# update the IP address in inventory/hosts.yml 
# ansible compute01 -m ping #to check we can reach the server
# ansible-playbook [--check] ./compute.yml [--tags <role>]

- hosts: compute01
  remote_user: admin #log in as admin
  become: yes        #but sudo to root to run the config commands

  tasks:
    # install required packages
    - include_role:
        name: install-packages
        apply: { tags: install-packages }
      tags: install-packages

    # upgrade packages to latest and reboot if any package was changed
    - include_role:
        name: security-updates
        apply: { tags: security-updates }
      tags: security-updates

    # turn on firewall, allow ssh
    - include_role:
        name: firewall
        apply: { tags: firewall }
      tags: firewall

    # setup raid0 using four block devices
    - include_role:
        name: setup-raid0
        apply: { tags: setup-raid0 }
      tags: setup-raid0

    # install munge authentication
    - include_role:
        name: munge
        apply: { tags: munge }
      tags: munge

    # install slurm
    - include_role:
        name: slurm
        apply: { tags: slurm }
      tags: slurm

    # create mutein user
    - include_role:
        name: create-user
        apply: { tags: create-user }
      tags: create-user

