---

#determine if md0 device exists, trigger handler if missing
- name: check raid0 active
  shell: |
    grep -c -e '^ARRAY /dev/md0' /etc/mdadm/mdadm.conf | cat
  register: check_raid0
  changed_when: "check_raid0.stdout == '0'"
  notify:
    - create raid0

- name: create xfs filesystem
  community.general.filesystem:
    fstype: xfs
    dev: /dev/md0

- name: mount xfs filesystem
  ansible.posix.mount:
    path: /mnt/raid0
    src: /dev/md0
    fstype: xfs
    opts: rw,relatime,attr2,inode64,noquota
    state: mounted
