---
id: 'PRAM'
qsub_id: 'pram'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga_2_genebackparams'
time: '1:00:0'
dependency: '-1'
array: 0
inputs: "repairs=5@split=1000"
active: 'Y'
---
id: 'VRAM'
qsub_id: 'vram'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga_2_genevarparams'
time: '1:00:0'
dependency: '-1'
array: 0
inputs: "@variant=*@vsplit=50"
active: 'Y'
---