---
id: 'Foldx1'
qsub_id: 'foldx_agg'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga05a_aggddg'
time: '1:00:0'
dependency: '-1'
array: 0
inputs: "repairs=1"
active: 'Y'
---
id: 'Foldx2'
qsub_id: 'foldx_varagg'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga05b_singlesagg'
time: '1:00:0'
dependency: 'Foldx1'
array: 0
inputs: "repairs=1@variant=*"
active: 'Y'
---
id: 'Foldx3'
qsub_id: 'genestitch'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga06_genestitch'
time: '1:00:0'
dependency: 'Foldx2'
array: 0
inputs: ""
active: 'Y'
---