---
id: 'REP'
qsub_id: 'repair'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga__runner'
time: '10:00:0'
cores: "4"
dependency: '-1'
array: -1
arrayfile: "pdbs"
inputs: "runs=c@repairs=10"
active: 'Y'
---