---
id: 'AGG'
qsub_id: 'foldx_agg'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga__runner'
time: '1:00:0'
cores: "1"
dependency: '-1'
array: 0
inputs: "runs=hij@repairs=x@variant=*"
active: 'Y'
---