---
id: '1'
qsub_id: 'geneprot02'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga01_genestoproteins'
time: '1:00:0'
dependency: '-1'
array: 0
inputs: ""
active: 'Y'
---
id: '1'
qsub_id: 'allgenes'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga01w_geneswait'
time: '1:00:0'
dependency: '-1'
array: 0
inputs: ""
active: 'Y'
---