---
id: 'Foldx1'
qsub_id: 'foldx_repair'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga02_repair'
time: '3:00:0'
dependency: '-1'
array: 100
inputs: "repairs=1"
active: 'Y'
---
id: 'Foldx2'
qsub_id: 'foldx_params'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga03a_makeparams'
time: '1:00:0'
dependency: 'Foldx1'
array: 0
inputs: "repairs=1@split=100"
active: 'Y'
---
id: 'Foldx3'
qsub_id: 'wait_posscan'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga04a_posscan'
time: '10:00:0'
dependency: 'Foldx2'
array: 0
inputs: "repairs=1"
active: 'Y'
---
id: 'Foldx5'
qsub_id: 'foldx_varp'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga03b_singlesparams'
time: '1:00:0'
dependency: 'Foldx1'
array: 0
inputs: "repairs=1@variant=*@split=20"
active: 'Y'
---
id: 'Foldx6'
qsub_id: 'wait_varscan'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga04b_singlescan_wait'
time: '10:00:0'
dependency: 'Foldx5'
array: 0
inputs: "repairs=1@variant=*"
active: 'Y'
---