---
id: 'TASKS'
qsub_id: 'foldx_posscan'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga__runner'
time: '48:00:0'
dependency: '-1'
array: -1
arrayfile: "params"
inputs: "runs=f@repairs=10"
active: 'Y'
---
id: 'VTASKS'
qsub_id: 'foldx_varscan'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga__runner'
time: '10:00:0'
dependency: '-1'
array: -1
arrayfile: "vparams"
inputs: "runs=g@repairs=10@variant=*"
active: 'N'
--- 