---
id: 'AGG'
qsub_id: 'foldx_varagg'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga05b_singlesagg'
time: '1:00:0'
dependency: '-1'
array: 0
inputs: "runs=hij@repairs=5@variant=*"
active: 'Y'
---