---
id: 'PRAM'
qsub_id: 'pram'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga__runner'
time: '1:00:0'
dependency: '-1'
array: 0
inputs: "runs=de@repairs=5@split=100@vsplit=20@variant=*"
active: 'Y'
---