---
id: 'PRAM'
qsub_id: 'pram'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga__runner'
time: '1:00:0'
dependency: '-1'
array: 0
inputs: "runs=d@repairs=10@split=500@vsplit=100@variant=*"
active: 'Y'
--- 