---
id: 'TASKS'
qsub_id: 'untasks'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga__runner'
time: '48:00:0'
cores: "8"
dependency: '-1'
array: -1
arrayfile: "unparams"
inputs: "runs=f@repairs=10@missing=Y"
active: 'Y'
---
id: 'VTASKS'
qsub_id: 'unvtasks'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga__runner'
time: '48:00:0'
cores: "8"
dependency: '-1'
array: -1
arrayfile: "vunparams"
inputs: "runs=f@repairs=10@missing=Y"
active: 'Y'
---