---
id: 'PRAM'
qsub_id: 'pram'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga__runner'
time: '1:00:0'
cores: "1"
dependency: '-1'
array: 0
inputs: "runs=d@repairs=10@chunk=10@vchunk=50@variant=*"
active: 'Y'
---
id: 'VPRAM'
qsub_id: 'vpram'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga__runner'
time: '1:00:0'
cores: "1"
dependency: '-1'
array: 0
inputs: "runs=e@repairs=10@chunk=10@vchunk=50@variant=*"
active: 'Y'
--- 