---
id: 'PRAM'
qsub_id: 'pram'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga__runner'
time: '5:00:0'
cores: "1"
dependency: '-1'
array: 0
inputs: "runs=de@repairs=10@chunk=20@vchunk=50@variant=*"
active: 'Y'
---