---
id: 'TASKS'
qsub_id: 'foldx_posscan'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga__runner'
time: '48:00:0'
dependency: '-1'
array: -1
arrayfile: "unparams"
inputs: "runs=f@repairs=5@missing=Y"
active: 'Y'
---