---
id: 'REP'
qsub_id: 'foldx_repair'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga__runner'
time: '5:00:0'
dependency: '-1'
array: -1
arrayfile: "pdbs"
inputs: "runs=c@repairs=5"
active: 'Y'
---