---
id: 'PRAM'
qsub_id: 'pram'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga_3_pdbbackparams'
time: '1:00:0'
dependency: '-1'
array: 0
inputs: "split=1000"
active: 'Y'
---
id: 'VRAM'
qsub_id: 'vram'
pipe_dir: 'Pipelines/geneanalysis/python/'
script: 'ga_3_pdbvarparams'
time: '1:00:0'
dependency: '-1'
array: 0
inputs: "@variant=*@vsplit=50"
active: 'N'
---