# This workflow will runs pytest
# For more information see: https://www.techiediaries.com/python-unit-tests-github-actions/
# 

name: Run Python Tests
on:
  push:
    branches: [main, testing]
  pull_request:
    branches: [main]

jobs:
  pytest-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Don't we also need to install the conda env?
      - name: Run tests with pytest
        run: |
          export MUT_DIR=$PWD
          export MUT_DATA=~/549_mutein
          source Pipelines/config/mutein_fixed_settings
          pytest
